name: combined_animation
description: A combined animation widget, contains alignment, opacity, transform, size for enter and leave a widget.
version: 0.3.0
homepage: https://github.com/shirne/combined_animation

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

